config/routes.rb
Depot::Application.routes.draw do
  resources :venues

  resources :stands

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  resources :products do
    get :who_bought, :on => :member
  end

  match 'thanks' => 'sessions#thanks_page'

  root :to => 'venues#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  def add_product(product_id)
    current_item = line_items.where(:product_id => product_id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = LineItem.new(:product_id=>product_id)
      line_items << current_item
    end
    current_item 
  end
    
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
  def total_items
    line_items.sum(:quantity)
  end
  
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  PAYMENT_TYPES = [ "Cash", "Credit card", "PayPal"]
  
  validates :name, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  validates :image_url, :format => {
    :with	=> %r{\.(gif|jpg|png)$}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }
  
  has_many :line_items
  has_many :orders, :through => :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.count.zero?
      return true
    else
      errors[:base] << "Line Items present"
      return false
    end
  end
  
end

app/models/stand.rb
class Stand < ActiveRecord::Base
end

app/models/user.rb
#---
# Excerpted from "Agile Web Development with Rails, 4rd Ed.",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
require 'digest/sha2'

class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
 
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader   :password

  validate  :password_must_be_present
  
  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end
  
  # 'password' is a virtual attribute
  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  
  after_destroy :ensure_an_admin_remains

  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end     

  private

    def password_must_be_present
      errors.add(:password, "Missing password") unless hashed_password.present?
    end
  
    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/no_www_helper.rb
module NoWwwHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stands_helper.rb
module StandsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/admin/index.html.erb
<h1>Welcome!</h1>
We have <%= pluralize(@total_orders, "order") %> in the queue.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html> <head>
<!--<title>Stadium Express</title> -->
<%= stylesheet_link_tag "scaffold" %> <%= stylesheet_link_tag "depot", :media => "all" %>
 <%= javascript_include_tag :defaults %> <%= csrf_meta_tag %>
</head> 

<body	id="store" >
	<div id="banner"> 
		<%= link_to image_tag("logo2.jpg", :size => "400x200", :border =>0), root_path %>
	<!--	<%= @page_title || "      Stadium Express" %>-->
		</div> 
		
		<div id="columns">
		
			<% if !session[:user_id] %>		
		
				<div id="stripe">
					<%= link_to "Vendor Login", login_path%> <br/>
				</div>
			
				<div id="main">
					<%= yield %>
				</div>
			<% end %>
		
		
			<% if session[:user_id] %>
				<div id="side2"> 
			
					<%= link_to "User Home", root_path%> <br/>

					<%= link_to 'Orders',	orders_path	%><br />
					<%= link_to 'Products', products_path %><br />
					<%= link_to 'Users',	users_path	%><br />
					<%= button_to 'Logout', logout_path, :method => :delete	%>
				</div> 
		
				<div id="main2">
					<%= yield %>
				</div> 	
			<% end %>		
	</div>

	
</body> 
</html>
			

app/views/notifier/order_received.text.erb
Dear <%= @order.name %>

Thank you for your recent order from Stadium Express!

You ordered the following items: 

<%= render @order.line_items %> 

Come down to the Stadium Express Stand to pick up your order. 

______


Again, thank you for participating! If you have any feedback regarding the Stadium Express product, please do not hesitate to reach out to us. Either come tell us at the stand or email us at Lindsey.eatough@gmail.com.

Also, don’t forget - The Penn Relays are coming back to historic Franklin Field on April 28-30. See the best Track and Field athletes in the world compete and witness a true Philadelphia tradition. Tickets are available now by calling 1–855–UofP–TIX or online at ThePennRelays.com.

app/views/notifier/order_shipped.html.erb
<h3>Stadium Express Order Ready</h3> <p>
This is just to let you know that your recent order is ready:
</p>
<table> <tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items %>
</table>

app/views/notifier/order_shipped.text.erb
Notifier#order_shipped

<%= @greeting %>, find me in app/views/app/views/notifier/order_shipped.text.erb